version: '3.9'
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:80'
  redis-server:
    image: bitnami/redis:6.2-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
    restart: always
  visits-api:
    build:
      context: .
      dockerfile: VisitsApi/Dockerfile
    environment:
      - RedisConnectionString=redis-server
    depends_on:
      - redis-server
    restart: always
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - visits-api
    restart: always
volumes:
  redis_data: