name: Deploy App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nkosiv/app-test -f frontend/Dockerfile.dev .
      - run: docker run -e CI=true nkosiv/app-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "test compose app from a course"
          environment_name: "testcomposeappfromacourse-env"
          existing_bucket_name: elasticbeanstalk-eu-north-1-444932218389
          region: "eu-north-1"
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
